# Generated by Django 2.1.7 on 2019-10-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interruptions_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RPID', models.CharField(max_length=50)),
                ('BTS_NAME', models.CharField(max_length=50)),
                ('BTS_TRF_CAT', models.CharField(max_length=50)),
                ('SSA', models.CharField(max_length=50)),
                ('SDCA', models.CharField(max_length=50)),
                ('CIRCLE', models.CharField(max_length=50)),
                ('MAKE', models.CharField(max_length=50)),
                ('TECH', models.CharField(max_length=50)),
                ('SITE_TYPE', models.CharField(max_length=50)),
                ('DOWN_DATE', models.CharField(max_length=50)),
                ('DOWN_TIME', models.CharField(max_length=50)),
                ('CLEARED_DATE', models.CharField(max_length=50)),
                ('CLEARED_TIME', models.CharField(max_length=50)),
                ('REASON', models.CharField(max_length=100)),
                ('DURATION', models.FloatField(max_length=50)),
            ],
        ),
    ]
