# Generated by Django 2.1.7 on 2019-10-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nsn3g_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField()),
                ('PLMN_name', models.CharField(max_length=100)),
                ('RNC_name', models.CharField(max_length=100)),
                ('WBTS_name', models.CharField(max_length=100)),
                ('WBTS_ID', models.CharField(max_length=100)),
                ('WCEL_name', models.CharField(max_length=100)),
                ('WCEL_ID', models.CharField(max_length=100)),
                ('RRC_CONN_SUCC_RATE', models.FloatField()),
                ('RRC_Connection_Setup_Completed', models.CharField(max_length=100)),
                ('RRC_Setup_Attempts', models.CharField(max_length=100)),
                ('CS_RAB_Setup_Success_Rate', models.FloatField()),
                ('RAB_setup_completed_for_CS_Voice_calls', models.IntegerField()),
                ('RAB_Attempts_CS_Voice', models.CharField(max_length=100)),
                ('R99_stp_SR_Usr', models.FloatField()),
                ('R99_Rab_Succ', models.CharField(max_length=100)),
                ('R99_Rab_Attempts', models.CharField(max_length=100)),
                ('HSDPA_stp_SR_Usr', models.FloatField()),
                ('HSDPA_Succ', models.CharField(max_length=100)),
                ('HSDPA_att', models.CharField(max_length=100)),
                ('HSUPA_stp_SR_Usr', models.FloatField()),
                ('HSUPA_Rab_Success', models.CharField(max_length=100)),
                ('HSUPA_Rab_Attempts', models.CharField(max_length=100)),
                ('Voice_DCR', models.FloatField()),
                ('CS_RAB_Drop_Nom', models.CharField(max_length=100)),
                ('CS_Rab_Release', models.CharField(max_length=100)),
                ('R99_PS_DROP_RATE', models.FloatField()),
                ('R99_DROP_COUNT', models.CharField(max_length=100)),
                ('R99_REL_COUNT', models.CharField(max_length=100)),
                ('HSDPA_CALL_DROP_RATE', models.FloatField()),
                ('HSDPA_CALL_DROP', models.IntegerField()),
                ('HSDPA_CALL_REL', models.CharField(max_length=100)),
                ('HSUPA_CALL_DROP_RATE', models.FloatField()),
                ('HSUPA_CALL_DROP', models.IntegerField()),
                ('HSUPA_CALL_REL', models.CharField(max_length=100)),
                ('Soft_HO_Success_rate_RT', models.FloatField()),
                ('SUCC_UPDATES_ON_SHO_FOR_RT', models.CharField(max_length=100)),
                ('Soft_HO_Update_Attempts_RT', models.CharField(max_length=100)),
                ('Inter_sys_RT_Hard_HOSR', models.FloatField()),
                ('RT_IRAT_SUCC', models.CharField(max_length=100)),
                ('RT_IRAT_ATT', models.CharField(max_length=100)),
                ('Inter_sys_NRT_Hard_HOSR', models.FloatField()),
                ('NRT_IRAT_SUCC', models.CharField(max_length=100)),
                ('NRT_IRAT_ATT', models.CharField(max_length=100)),
                ('Total_CS_traffic_Erl', models.FloatField()),
                ('NRT_DCH_MACd_throughput_DL', models.FloatField()),
                ('NRT_DCH_MACd_throughput_UL', models.FloatField()),
                ('Average_RTWP', models.FloatField()),
                ('Average_number_of_simultaneous_HSDPA_users', models.CharField(max_length=100)),
                ('Max_simult_HSDPA_users', models.CharField(max_length=100)),
                ('Active_HS_DSCH_cell_thr', models.CharField(max_length=100)),
                ('HSUPA_Datapayload_MB', models.FloatField()),
                ('HSDPA_Payload_MB', models.FloatField()),
                ('Active_HSUPA_cell_thp', models.CharField(max_length=100)),
                ('CSSR', models.FloatField()),
                ('Video_DCR', models.FloatField()),
                ('PS_Congestion_due_to_CE_3G', models.FloatField()),
                ('PS_Congestion_due_to_IUB_3G', models.FloatField()),
                ('PS_Congestion_due_to_Power_3G', models.FloatField()),
            ],
        ),
    ]
