# Generated by Django 2.1.7 on 2019-10-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_auto_20191010_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsn3g_table',
            name='DATE',
            field=models.DateField(auto_now_add=True),
        ),
    ]
