# Generated by Django 2.1.7 on 2019-10-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0006_auto_20191010_1935'),
    ]

    operations = [
        migrations.DeleteModel(
            name='nsn3g_table',
        ),
    ]
