# Generated by Django 2.1.7 on 2019-10-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0009_auto_20191010_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsn3g_table',
            name='DATE',
            field=models.DateField(),
        ),
    ]
