# Generated by Django 2.1.7 on 2019-10-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0010_auto_20191010_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsn3g_table',
            name='DATE',
            field=models.CharField(max_length=100),
        ),
    ]
