# Generated by Django 2.1.7 on 2019-10-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0012_auto_20191010_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsn3g_table',
            name='DATE',
            field=models.DateField(auto_now=True),
        ),
    ]
