# Generated by Django 2.1.7 on 2019-10-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0014_zte3g_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zte3g_table',
            name='dl_data',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='zte3g_table',
            name='ul_data',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
