# Generated by Django 2.1.7 on 2019-10-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0015_auto_20191010_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zte3g_table',
            name='dl_data',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='zte3g_table',
            name='ul_data',
            field=models.FloatField(),
        ),
    ]
